version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    resource_class: large
    environment:
      http_proxy: http://10.112.1.184:8080
      https_proxy: http://10.112.1.184:8080
    steps:
      # proxy setting
      - run: curl -sL https://art.sec.samsung.net/artifactory/tools/CircleCI/scripts/set_proxy_setting.sh | sh

      - checkout

      # basis toolchain
      - run: sudo apt-get update && sudo apt-get install -qq build-essential git cmake automake

      # build dependencies
      - run: sudo apt-get install -qq libboost-all-dev libsqlite3-dev libsystemd-dev

      # gflag & glog & gtest
      - run: cd /usr/src && sudo git clone https://github.com/google/glog.git && sudo git clone https://github.com/google/googletest.git && sudo git clone https://github.com/gflags/gflags.git
      - run: cd /usr/src/gflags && sudo cmake . && sudo make && sudo make install
      - run: cd /usr/src/glog && sudo cmake . && sudo make && sudo make install
      - run: cd /usr/src/googletest && sudo cmake . && sudo make && sudo make install

      # ViST build & run & test
      - run: cd /home/circleci/project && sudo make && sudo make install
      - run: sudo vistd & sudo vist-test 
