version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    resource_class: large
    environment:
      http_proxy: http://10.112.1.184:8080
      https_proxy: http://10.112.1.184:8080
    steps:
      - run: no_proxy=165.213.149.164 curl -sL http://165.213.149.164/scripts/set_proxy_setting.sh | bash -
      - checkout
      # basis toolchain
      - run: sudo apt-get update && sudo apt-get install -qq build-essential git cmake automake
      # osquery core dependencies
      - run: sudo apt-get install -qq libboost-all-dev libreadline-dev
      - run: cd /usr/src && sudo git clone https://github.com/gflags/gflags.git
      - run: cd /usr/src/gflags && sudo git checkout v2.2.1 && sudo cmake . && sudo make && sudo make install

      # thrift
      - run: sudo apt-get install -qq libevent-dev libtool flex bison pkg-config g++ libssl-dev
      - run: sudo apt-get install -qq libssl1.0-dev
      - run: cd /usr/src && sudo git clone https://github.com/apache/thrift.git
      - run: cd /usr/src/thrift && sudo git checkout 0.9.3 && sudo find ./ -name "*.cpp" -exec sed -i 's/SSLv3_method/SSLv23_method/g' {} \;
      - run: cd /usr/src/thrift && sudo ./bootstrap.sh && sudo ./configure LDFLAGS=-L/usr/lib/x86_64-linux-gnu && sudo make && sudo make install
      # glog & gtest
      - run: cd /usr/src && sudo git clone https://github.com/google/glog.git && sudo git clone https://github.com/google/googletest.git
      - run: cd /usr/src/glog && sudo cmake . && sudo make && sudo make install
      - run: cd /usr/src/googletest && sudo cmake . && sudo make && sudo make install
      # rocksdb
      - run: cd /usr/src && sudo git clone https://github.com/facebook/rocksdb.git
      - run: sudo apt-get install -qq libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
      - run: cd /usr/src/rocksdb && sudo make static_lib && sudo make install
      # built-in table dependencies 
      - run: sudo apt-get install -qq python-pip && sudo pip install Jinja2
      - run: sudo apt-get install -qq libprocps-dev libsystemd-dev libudev-dev iptables-dev

      # Tizen osquery build & test
      - run: cd /home/circleci/project && sudo make
      - run: cd /home/circleci/project/build/osquery && sudo ./osquery-test
      - run: cd /home/circleci/project && sudo make test
