#!/bin/bash
dbus-send --system --type=method_call --print-reply --dest=org.tizen.DevicePolicyManager \
				 /org/tizen/DevicePolicyManager/Syspopup \
				 org.tizen.DevicePolicyManager.Syspopup.show \
				 string:${1}

