#  Copyright (c) 2019 Samsung Electronics Co., Ltd All Rights Reserved
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License

MACRO(ADD_OSQUERY_LIBRARY CROSS_PLATFORM TARGET)
	ADD_LIBRARY(${TARGET} OBJECT ${ARGN})

	IF(${CROSS_PLATFORM})
		LIST(APPEND ${TARGET_OSQUERY_LIB}_SRCS $<TARGET_OBJECTS:${TARGET}>)
		SET(${TARGET_OSQUERY_LIB}_SRCS ${${TARGET_OSQUERY_LIB}_SRCS} PARENT_SCOPE)
	ELSE()
		LIST(APPEND ${TARGET_OSQUERY_LIB_ONLY_GBS}_SRCS $<TARGET_OBJECTS:${TARGET}>)
		SET(${TARGET_OSQUERY_LIB_ONLY_GBS}_SRCS
			${${TARGET_OSQUERY_LIB_ONLY_GBS}_SRCS} PARENT_SCOPE)
	ENDIF()
ENDMACRO(ADD_OSQUERY_LIBRARY)

MACRO(ADD_OSQUERY_TEST CROSS_PLATFORM)
	IF(${CROSS_PLATFORM})
		LIST(APPEND ${TARGET_OSQUERY_LIB}_TESTS ${ARGN})
		SET(${TARGET_OSQUERY_LIB}_TESTS ${${TARGET_OSQUERY_LIB}_TESTS} PARENT_SCOPE)
	ELSE()
		LIST(APPEND ${TARGET_OSQUERY_LIB_ONLY_GBS}_TESTS ${ARGN})
		SET(${TARGET_OSQUERY_LIB_ONLY_GBS}_TESTS
			${${TARGET_OSQUERY_LIB_ONLY_GBS}_TESTS} PARENT_SCOPE)
	ENDIF()
ENDMACRO(ADD_OSQUERY_TEST)

MACRO(ADD_OSQUERY_LINK CROSS_PLATFORM)
	IF(${CROSS_PLATFORM})
		LIST(APPEND ${TARGET_OSQUERY_LIB}_DEPS ${ARGN})
		SET(${TARGET_OSQUERY_LIB}_DEPS ${${TARGET_OSQUERY_LIB}_DEPS} PARENT_SCOPE)
	ELSE()
		LIST(APPEND ${TARGET_OSQUERY_LIB_ONLY_GBS}_DEPS ${ARGN})
		SET(${TARGET_OSQUERY_LIB_ONLY_GBS}_DEPS
			${${TARGET_OSQUERY_LIB_ONLY_GBS}_DEPS} PARENT_SCOPE)
	ENDIF()
ENDMACRO(ADD_OSQUERY_LINK)

MACRO(TARGET_OSQUERY_LINK_WHOLE TARGET LIBRARY)
	TARGET_LINK_LIBRARIES(${TARGET} "-Wl,-whole-archive")
	TARGET_LINK_LIBRARIES(${TARGET} ${LIBRARY})
	TARGET_LINK_LIBRARIES(${TARGET} "-Wl,-no-whole-archive")
ENDMACRO(TARGET_OSQUERY_LINK_WHOLE)

MACRO(ADD_OSQUERY_MODULE TARGET)
	ADD_LIBRARY(${TARGET} SHARED ${ARGN})
	TARGET_LINK_LIBRARIES(${TARGET} dl)
	ADD_DEPENDENCIES(${TARGET} ${TARGET_OSQUERY_LIB} glog)
	SET_TARGET_PROPERTIES(${TARGET} PROPERTIES COMPILE_FLAGS "-fPIC")
	SET_TARGET_PROPERTIES(${TARGET} PROPERTIES OUTPUT_NAME ${TARGET})
ENDMACRO(ADD_OSQUERY_MODULE)
